#!/bin/bash

# Given a set of WARC file paths, or a directory that contains WARC files,
# return a count of the WARC records. The WARC files may be gzipped, or
# uncompressed.

SCRIPT_DIR=`dirname $0`
PROJ_DIR=${SCRIPT_DIR}/../../..

java -cp $PROJ_DIR/target/WARCUtils-1.0-SNAPSHOT.jar edu.stanford.warcutils.warcreader.WarcCounter $@